x-templates:
  minecraft-server-environment: &minecraft-server-environment
    EULA: true
    TYPE: limbo
    LIMBO_BUILD: 46

  minecraft-server: &minecraft-server
    image: itzg/minecraft-server:latest
    networks:
      - minecraft
    environment:
      <<: *minecraft-server-environment

services:
  gate:
    image: ghcr.io/kasefuchs/lazygate:latest
    build:
      context: ..
      dockerfile: build/Dockerfile
    ports:
      - "25565:25565"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "../configs/gate.docker.yml:/config.yml:ro"
    networks:
      - minecraft
    env_file:
      - ../configs/gate.docker.env

  notorious:
    <<: *minecraft-server
    ports:
      - "33019:30000"
    labels:
      lazygate.server: notorious
      lazygate.time.minimumOnline: 30s
      lazygate.time.inactivityThreshold: 30s
      lazygate.disconnectReasons.starting: Notorious is currently starting!
      lazygate.disconnectReasons.startFailed: Notorious is failed to start :(
    volumes:
      - "notorious:/data"
    environment:
      <<: *minecraft-server-environment
      CUSTOM_SERVER_PROPERTIES: |
        tab-header=Notorious
        bungeecord=false
        allow-flight=true

  luminescence:
    <<: *minecraft-server
    ports:
      - "37666:30000"
    labels:
      lazygate.server: luminescence
      lazygate.time.minimumOnline: 2m
      lazygate.time.inactivityThreshold: 5m
      lazygate.disconnectReasons.starting: Luminescence is currently starting!
      lazygate.disconnectReasons.startFailed: Luminescence is failed to start :(
    volumes:
      - "luminescence:/data"
    environment:
      <<: *minecraft-server-environment
      CUSTOM_SERVER_PROPERTIES: |
        tab-header=Luminescence
        bungeecord=false
        allow-flight=true

volumes:
  notorious: {}
  luminescence: {}

networks:
  minecraft: {}
