---
x-templates:
  minecraft-server-environment: &minecraft-server-environment
    EULA: true
    TYPE: limbo
    LIMBO_BUILD: 46

  minecraft-server: &minecraft-server
    image: itzg/minecraft-server:latest
    networks:
      - minecraft
    environment:
      <<: *minecraft-server-environment

services:
  gate:
    image: ghcr.io/kasefuchs/lazygate:latest
    build:
      context: ..
      dockerfile: build/Dockerfile
    ports:
      - "25565:25565"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ../configs/gate.docker.yaml:/config.yml:ro
    networks:
      - minecraft
    env_file:
      - ../configs/gate.docker.env

  notorious:
    <<: *minecraft-server
    ports:
      - "33019:30000"
    labels:
      lazygate.allocation.server: notorious
      lazygate.allocation.time.minimumOnline: 30s
      lazygate.allocation.time.inactivityThreshold: 30s
      lazygate.allocation.queues: wait,kick
      lazygate.queue.wait.timeout: 10s
      lazygate.queue.wait.pingInterval: 2s
      lazygate.queue.kick.reason: Notorious is currently starting!
    volumes:
      - notorious:/data
    environment:
      <<: *minecraft-server-environment
      CUSTOM_SERVER_PROPERTIES: |
        tab-header=Notorious
        bungeecord=false
        allow-flight=true

  luminescence:
    <<: *minecraft-server
    ports:
      - "33020:30000"
    labels:
      lazygate.allocation.server: luminescence
      lazygate.allocation.time.minimumOnline: 2m
      lazygate.allocation.time.inactivityThreshold: 5m
      lazygate.allocation.queues: wait,kick
      lazygate.queue.wait.timeout: 10s
      lazygate.queue.wait.pingInterval: 2s
      lazygate.queue.kick.reason: Luminescence is currently starting!
    volumes:
      - luminescence:/data
    environment:
      <<: *minecraft-server-environment
      CUSTOM_SERVER_PROPERTIES: |
        tab-header=Luminescence
        bungeecord=false
        allow-flight=true

volumes:
  notorious: {}
  luminescence: {}

networks:
  minecraft: {}
